CREATE TABLE categoria(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO categoria (NOME) VALUES ('LAZER');
INSERT INTO categoria (NOME) VALUES ('ALIMENTACAO');
INSERT INTO categoria (NOME) VALUES ('SUPERMERCADO');
INSERT INTO categoria (NOME) VALUES ('FARMACIA');
INSERT INTO categoria (NOME) VALUES ('OUTROS');